"""
action_selector.py
Recon Rover V1 - AI Decision Engine

Translates the prioritized CandidateAction into standard Semantic Events.
"""

from event_bus import (
    EventBus, MovementRequestEvent, EmergencyStopRequested, 
    DecisionUpdated, DecisionConfidenceUpdated, 
    ReturnHomeRequested, ExplorationRequested, AvoidObstacleRequested,
    GoalSelected
)
from .ai_blackboard import CandidateAction
from logger import Logger

class ActionSelector:
    def __init__(self, event_bus: EventBus):
        self.event_bus = event_bus
        self.log = Logger.get("ActionSelector")

    def execute(self, decision: CandidateAction):
        """Publishes the corresponding semantic event."""
        
        # 1. Publish raw decision data for telemetry / UI
        self.event_bus.publish(DecisionUpdated(intent=decision.intent, parameters=decision.parameters))
        self.event_bus.publish(DecisionConfidenceUpdated(confidence=decision.confidence))
        
        # 2. Map to semantic intents
        if decision.intent == "EmergencyStop":
            self.event_bus.publish(EmergencyStopRequested(reason="AI Rule Engine Override"))
            self.event_bus.publish(MovementRequestEvent(action="Stop", speed_factor=0.0))
            
        elif decision.intent == "ReturnHome":
            self.event_bus.publish(ReturnHomeRequested())
            
        elif decision.intent == "Patrol":
            self.event_bus.publish(ExplorationRequested())
            
        elif decision.intent == "AvoidObstacle":
            self.event_bus.publish(AvoidObstacleRequested())

        elif decision.intent == "AvoidHazard":
            # Just issue a halt - Navigation layer could handle recovery
            self.event_bus.publish(MovementRequestEvent(action="Stop", speed_factor=0.0))
            
        elif decision.intent == "GreetHuman":
            self.event_bus.publish(GoalSelected(goal_name="InteractHuman"))
            
        elif decision.intent == "ProcessSpeech":
            self.event_bus.publish(GoalSelected(goal_name="Listen"))
            
        elif decision.intent == "Idle":
            self.log.debug("Intent is Idle. Doing nothing.")
            
        else:
            self.log.warning(f"Unknown intent generated by AI: {decision.intent}")
