"""
action_selector.py
Recon Rover V1 - AI Decision Engine

Translates the prioritized CandidateAction into standard Semantic Events.
"""

from event_bus import (
    EventBus, MovementRequest, BehaviorRequest, MissionRequest, DecisionUpdated, DecisionConfidenceUpdated, EmergencyDecision
)
from .ai_blackboard import CandidateAction
from logger import Logger

class ActionSelector:
    def __init__(self, event_bus: EventBus):
        self.event_bus = event_bus
        self.log = Logger.get("ActionSelector")

    def execute(self, decision: CandidateAction):
        """Publishes the corresponding semantic event."""
        
        # 1. Publish raw decision data for telemetry / UI
        self.event_bus.publish(DecisionUpdated(intent=decision.intent, parameters=decision.parameters))
        self.event_bus.publish(DecisionConfidenceUpdated(confidence=decision.confidence))
        
        # 2. Map to semantic intents
        if decision.intent == "EmergencyStop":
            self.event_bus.publish(EmergencyDecision(reason="System Fault"))
            self.event_bus.publish(MovementRequest(vector=[0, 0, 0]))
            
        elif decision.intent == "ReturnHome":
            self.event_bus.publish(MissionRequest(command="ReturnToBase"))
            
        elif decision.intent == "Patrol":
            self.event_bus.publish(BehaviorRequest(behavior="PatrolArea"))
            
        elif decision.intent == "GreetHuman":
            self.event_bus.publish(BehaviorRequest(behavior="InteractHuman"))
            
        elif decision.intent == "ProcessSpeech":
            self.event_bus.publish(BehaviorRequest(behavior="Listen", params=decision.parameters))
            
        elif decision.intent == "Idle":
            pass # Do nothing
            
        else:
            self.log.warning(f"Unknown intent generated by AI: {decision.intent}")
